/** Code extraction limits */
export const EXTRACTION_LIMITS = {
	maxFileSize: 100 * 1024,
	fileTreeMaxDepth: 4,
} as const

/** Glob patterns to ignore during file scanning */
export const IGNORE_PATTERNS = [
	"**/node_modules/**",
	"**/dist/**",
	"**/build/**",
	"**/out/**",
	"**/.next/**",
	"**/.nuxt/**",
	"**/.svelte-kit/**",
	"**/.astro/**",
	"**/.output/**",
	"**/.git/**",
	"**/.idea/**",
	"**/.vscode/**",
	"**/coverage/**",
	"**/__tests__/**",
	"**/*.test.*",
	"**/*.spec.*",
	"**/*.stories.*",
	"**/.storybook/**",
	"**/cypress/**",
	"**/e2e/**",
	"**/public/assets/**",
	"**/*.map",
	"**/CHANGELOG*",
	"**/LICENSE*",
	"**/.env*",
	"**/package-lock.json",
	"**/pnpm-lock.yaml",
	"**/yarn.lock",
] as const

/** File extensions to include in scanning */
export const INCLUDE_EXTENSIONS = [
	".tsx",
	".jsx",
	".vue",
	".svelte",
	".astro",
	".css",
	".scss",
	".sass",
	".less",
	".ts",
	".js",
	".mjs",
	".cjs",
	".svg",
	".json",
	// Template engines
	".html",
	".ejs",
	".pug",
	".hbs",
	".njk",
	".mustache",
] as const

/** Directory names to skip when building file tree */
export const TREE_IGNORE_DIRS = new Set([
	"node_modules",
	"dist",
	"build",
	"out",
	".next",
	".nuxt",
	".svelte-kit",
	".astro",
	".output",
	".git",
	".idea",
	".vscode",
	"coverage",
	"__tests__",
	".storybook",
	"cypress",
	"e2e",
	// AI tool configs
	".agent",
	".agents",
	".claude",
	".cursor",
	".codex",
	".opencode",
	".tanstack",
	".yarn",
	".pnpm",
	// Other non-source dirs
	"public",
	".github",
	".husky",
	"drizzle",
	"deploy",
	"charts",
])
