export { assembleDocuments } from "./doc-assembler.js"
export { assemblePrompts } from "./prompt-assembler.js"
export { resolveEnvironment } from "./resolve-environment.js"
export type { EnvironmentProfile } from "./resolve-environment.js"
export type { ProjectStructure } from "./resolve-structure.js"
